/**
 * Auto-Fix PR Creator — Git branch + GitHub Pull Request + Email notification
 *
 * Flow:
 *   1. Create branch: autofix/<timestamp>-<slug>
 *   2. Apply search/replace file patches
 *   3. Commit with structured message
 *   4. Push branch to GitHub
 *   5. Create Pull Request via GitHub REST API
 *   6. Send email alert to admin
 */

import fs from 'fs';
import { execSync } from 'child_process';

const GITHUB_API = 'https://api.github.com';

/**
 * Create a GitHub PR with the auto-fix changes.
 *
 * @param {object} fixResult - Output from errorAnalyzer: { rootCause, explanation, confidence, changes }
 * @param {object} errorEvent - { errorText, category, hash }
 * @param {object} options - { githubPat, githubRepo, appRoot, notifyEmail }
 * @returns {Promise<object>} - { success, prUrl, branchName, error? }
 */
export async function createFixPR(fixResult, errorEvent, options = {}) {
    const {
        githubPat = process.env.GITHUB_PAT,
        githubRepo = process.env.GITHUB_REPO || 'Abhishekjohri1998/Mantram',
        appRoot = process.env.AUTOFIX_APP_ROOT || '/home/ec2-user/Mantram',
        notifyEmail = process.env.AUTOFIX_NOTIFY_EMAIL || process.env.SUPERADMIN_NOTIFY_EMAIL,
    } = options;

    if (!githubPat) throw new Error('GITHUB_PAT is not set');
    if (!fixResult.changes || fixResult.changes.length === 0) {
        return { success: false, error: 'No changes to apply' };
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').substring(0, 16);
    const slug = createSlug(fixResult.rootCause);
    const branchName = `autofix/${timestamp}-${slug}`;

    try {
        // ── 1. Create branch from latest main ─────────────────────────────
        console.log(`🔀 AutoFix: Creating branch ${branchName}`);
        execGit(appRoot, 'fetch origin main');
        execGit(appRoot, `checkout -b ${branchName} origin/main`);

        // ── 2. Apply file patches ─────────────────────────────────────────
        const changedFiles = [];
        for (const change of fixResult.changes) {
            try {
                const content = fs.readFileSync(change.file, 'utf-8');
                if (!content.includes(change.search)) {
                    console.warn(`⚠️ AutoFix: Search string no longer found in ${change.file} — skipping`);
                    continue;
                }
                const updated = content.replace(change.search, change.replace);
                fs.writeFileSync(change.file, updated, 'utf-8');
                changedFiles.push(change.file);
                console.log(`   ✏️ Patched: ${change.file}`);
            } catch (patchErr) {
                console.error(`❌ AutoFix: Failed to patch ${change.file}:`, patchErr.message);
            }
        }

        if (changedFiles.length === 0) {
            // Cleanup: go back to main
            execGit(appRoot, 'checkout main');
            execGit(appRoot, `branch -D ${branchName}`);
            return { success: false, error: 'No files were successfully patched' };
        }

        // ── 3. Commit ─────────────────────────────────────────────────────
        const commitMsg = [
            `fix(autofix): ${fixResult.rootCause.substring(0, 72)}`,
            '',
            `Root Cause: ${fixResult.rootCause}`,
            `Explanation: ${fixResult.explanation}`,
            `Category: ${errorEvent.category}`,
            `Confidence: ${Math.round(fixResult.confidence * 100)}%`,
            `Files: ${changedFiles.map(f => f.split('/backend/')[1] || f).join(', ')}`,
            '',
            `🤖 Auto-generated by Mantram Log Watcher Agent`,
        ].join('\n');

        for (const f of changedFiles) {
            execGit(appRoot, `add "${f}"`);
        }
        execGit(appRoot, `commit -m "${commitMsg.replace(/"/g, '\\"')}"`);

        // ── 4. Push branch (use PAT-authenticated URL to avoid credential issues) ──
        console.log(`📤 AutoFix: Pushing branch ${branchName}`);
        const pushUrl = `https://x-access-token:${githubPat}@github.com/${githubRepo}.git`;
        execGit(appRoot, `push ${pushUrl} ${branchName}`);

        // ── 5. Create Pull Request via GitHub API ─────────────────────────
        const prBody = buildPRBody(fixResult, errorEvent, changedFiles);
        const pr = await createGitHubPR({
            githubPat,
            githubRepo,
            branchName,
            title: `🤖 Auto-Fix: ${fixResult.rootCause.substring(0, 80)}`,
            body: prBody,
        });

        // ── 6. Return to main ─────────────────────────────────────────────
        execGit(appRoot, 'checkout main');

        console.log(`✅ AutoFix: PR created — ${pr.html_url}`);

        // ── 7. Send email notification ────────────────────────────────────
        if (notifyEmail) {
            await sendAlertEmail(notifyEmail, pr, fixResult, errorEvent).catch(emailErr => {
                console.warn('⚠️ AutoFix: Email notification failed:', emailErr.message);
            });
        }

        return { success: true, prUrl: pr.html_url, branchName };

    } catch (err) {
        console.error('❌ AutoFix: PR creation failed:', err.message);
        // Cleanup: try to go back to main
        try { execGit(appRoot, 'checkout main'); } catch (_) { }
        try { execGit(appRoot, `branch -D ${branchName}`); } catch (_) { }
        return { success: false, error: err.message };
    }
}

// ── Git execution helper ──────────────────────────────────────────────────
function execGit(cwd, cmd) {
    const fullCmd = `git ${cmd}`;
    try {
        return execSync(fullCmd, { cwd, timeout: 30000, encoding: 'utf-8', stdio: 'pipe' });
    } catch (err) {
        // Redact any PAT tokens from error messages to prevent log leakage
        const safeCmd = fullCmd.replace(/x-access-token:[^@]+@/, 'x-access-token:***@');
        const safeErr = (err.stderr || err.message || '').replace(/x-access-token:[^@]+@/, 'x-access-token:***@');
        throw new Error(`Git command failed: ${safeCmd}\n${safeErr}`);
    }
}

// ── GitHub API: Create Pull Request ───────────────────────────────────────
async function createGitHubPR({ githubPat, githubRepo, branchName, title, body }) {
    const url = `${GITHUB_API}/repos/${githubRepo}/pulls`;

    const response = await fetch(url, {
        method: 'POST',
        headers: {
            'Accept': 'application/vnd.github+json',
            'Authorization': `Bearer ${githubPat}`,
            'X-GitHub-Api-Version': '2022-11-28',
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            title,
            body,
            head: branchName,
            base: 'main',
            draft: false,
        }),
    });

    if (!response.ok) {
        const errBody = await response.text();
        throw new Error(`GitHub API ${response.status}: ${errBody.substring(0, 300)}`);
    }

    const pr = await response.json();

    // Add labels
    try {
        await fetch(`${GITHUB_API}/repos/${githubRepo}/issues/${pr.number}/labels`, {
            method: 'POST',
            headers: {
                'Accept': 'application/vnd.github+json',
                'Authorization': `Bearer ${githubPat}`,
                'X-GitHub-Api-Version': '2022-11-28',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ labels: ['autofix', 'bot'] }),
        });
    } catch (_) { /* labels are optional, don't fail if labels don't exist */ }

    return pr;
}

// ── Build PR body ─────────────────────────────────────────────────────────
function buildPRBody(fixResult, errorEvent, changedFiles) {
    return `## 🤖 Auto-Fix Report

### Root Cause
${fixResult.rootCause}

### Explanation
${fixResult.explanation}

### Error Category
\`${errorEvent.category}\` — Confidence: **${Math.round(fixResult.confidence * 100)}%**

### Error Log
\`\`\`
${errorEvent.errorText.substring(0, 2000)}
\`\`\`

### Files Changed
${changedFiles.map(f => `- \`${f.split('/backend/')[1] || f}\``).join('\n')}

---

> ⚠️ **This PR was auto-generated by the Mantram Log Watcher Agent.**
> Please review the changes carefully before merging.
> The agent detected this error in the PM2 production logs and used Claude AI to generate a minimal fix.
`;
}

// ── Email notification ────────────────────────────────────────────────────
async function sendAlertEmail(to, pr, fixResult, errorEvent) {
    // Dynamically import the existing email utility
    const { sendEmail } = await import('../utils/email.js');

    const html = `
        <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 640px; margin: 0 auto; background: #0f0f23; color: #e2e8f0; border-radius: 16px; overflow: hidden; border: 1px solid rgba(255,255,255,0.05);">
            <div style="background: linear-gradient(135deg, #FF4D00, #ff6b2b); padding: 32px 24px; text-align: center;">
                <h1 style="margin: 0; font-size: 24px; color: #fff;">🤖 Auto-Fix PR Created</h1>
                <p style="margin: 8px 0 0; color: rgba(255,255,255,0.9); font-size: 14px;">Mantram Log Watcher Agent</p>
            </div>
            <div style="padding: 32px 24px;">
                <div style="background: rgba(255,77,0,0.08); border: 1px solid rgba(255,77,0,0.2); border-radius: 12px; padding: 20px; margin-bottom: 24px;">
                    <p style="margin: 0 0 8px; font-size: 12px; color: #FF4D00; text-transform: uppercase; font-weight: 700; letter-spacing: 0.05em;">Root Cause</p>
                    <p style="margin: 0; font-size: 15px; color: #e2e8f0; line-height: 1.5;">${fixResult.rootCause}</p>
                </div>
                <div style="margin-bottom: 24px;">
                    <p style="margin: 0 0 8px; font-size: 12px; color: #94a3b8; text-transform: uppercase; font-weight: 700;">Fix Details</p>
                    <p style="margin: 0; font-size: 14px; color: #cbd5e1; line-height: 1.6;">${fixResult.explanation}</p>
                </div>
                <div style="display: flex; gap: 16px; margin-bottom: 24px;">
                    <div style="flex: 1; background: rgba(255,255,255,0.03); border-radius: 8px; padding: 12px; text-align: center;">
                        <p style="margin: 0; font-size: 11px; color: #64748b; text-transform: uppercase;">Category</p>
                        <p style="margin: 4px 0 0; font-size: 14px; color: #e2e8f0; font-weight: 600;">${errorEvent.category}</p>
                    </div>
                    <div style="flex: 1; background: rgba(255,255,255,0.03); border-radius: 8px; padding: 12px; text-align: center;">
                        <p style="margin: 0; font-size: 11px; color: #64748b; text-transform: uppercase;">Confidence</p>
                        <p style="margin: 4px 0 0; font-size: 14px; color: #e2e8f0; font-weight: 600;">${Math.round(fixResult.confidence * 100)}%</p>
                    </div>
                </div>
                <div style="text-align: center; margin: 32px 0 16px;">
                    <a href="${pr.html_url}" style="display: inline-block; background: #FF4D00; color: #fff; text-decoration: none; padding: 14px 36px; border-radius: 10px; font-size: 15px; font-weight: 700;">Review PR on GitHub →</a>
                </div>
            </div>
            <div style="padding: 16px 24px; background: rgba(255,255,255,0.02); text-align: center; border-top: 1px solid rgba(255,255,255,0.05);">
                <p style="margin: 0; font-size: 11px; color: #475569;">Mantram AI — Autonomous Log Watcher Agent</p>
            </div>
        </div>
    `;

    await sendEmail({
        to,
        subject: `🤖 Auto-Fix PR: ${fixResult.rootCause.substring(0, 60)}`,
        html,
    });

    console.log(`📧 AutoFix: Email alert sent to ${to}`);
}

// ── Slug generator ────────────────────────────────────────────────────────
function createSlug(text) {
    return (text || 'unknown-error')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '')
        .substring(0, 40);
}
