const fs = require('fs');
const { chromium } = require('playwright');

async function getCookies() {
    console.log("Launching browser...");
    const browser = await chromium.launch({ headless: true });
    const context = await browser.newContext({
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    });
    const page = await context.newPage();

    console.log("Navigating to YouTube...");
    await page.goto('https://www.youtube.com', { waitUntil: 'domcontentloaded' });
    
    // Wait a bit for cookies to set and bot checks to pass
    await page.waitForTimeout(5000);

    // Try to click accept on cookie dialogs if present (Europe)
    try {
        await page.click('button[aria-label="Accept all"]', { timeout: 2000 });
        await page.waitForTimeout(2000);
    } catch (e) {}

    const cookies = await context.cookies();
    console.log(`Extracted ${cookies.length} cookies.`);

    // Convert to Netscape format for yt-dlp
    let cookieTxt = "# Netscape HTTP Cookie File\n# This file is generated by Playwright\n\n";
    for (const c of cookies) {
        const domain = c.domain;
        const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
        const path = c.path;
        const secure = c.secure ? 'TRUE' : 'FALSE';
        const expires = Math.round(c.expires || (Date.now() / 1000) + 31536000);
        const name = c.name;
        const value = c.value;
        cookieTxt += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}\n`;
    }

    fs.writeFileSync('youtube-cookies.txt', cookieTxt);
    console.log("Cookies saved to youtube-cookies.txt");

    await browser.close();
}

getCookies().catch(err => {
    console.error(err);
    process.exit(1);
});
