# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "43970544d2e2cfa2e02dc38b94b62af5"
name = "Mantram AI"
application_url = "https://mantram.ai"
embedded = true

[webhooks]
api_version = "2025-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://api.mantram.ai/api/shopify/webhooks/customers-redact"
  customer_data_request_url = "https://api.mantram.ai/api/shopify/webhooks/customers-data-request"
  shop_deletion_url = "https://api.mantram.ai/api/shopify/webhooks/shop-redact"
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_inventory,read_inventory,read_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://api.mantram.ai/api/shopify/callback",
  "https://api.mantram.ai/api/shopify/auth"
]
