# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3316fa753006b2de85d8cc512cb462c5"
name = "Mantram AI"
application_url = "https://mantram.ai"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  compliance_topics = [
    "customers/data_request",
    "customers/redact",
    "shop/redact"
  ]
  uri = "https://api.mantram.ai/api/shopify/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://api.mantram.ai/api/shopify/callback" ]
