/**
 * Q-Ads Presets — 13 preset definitions
 *
 * Each preset locks: cameraSignature, pacing, environmentDefault, register, cuts.
 * Engine rules are enforced universally by the Q-Ads Agent — not per-preset.
 *
 * Creative names only. No generic category names.
 * One source of truth — agent and frontend both import from here.
 */

export const Q_ADS_PRESETS = [

    // ─── GROUP 1: Creator / UGC ───────────────────────────────────────────────

    {
        id: 'first_look',
        name: 'First Look',
        tagline: 'Discovery in real time.',
        threeWordCamera: 'Handheld · Eye-level · Rack',
        registerSummary: 'Warm peer-to-peer. A friend sharing something real.',
        description: 'Someone encounters the product for the first time. Genuine micro-reactions — curiosity, examination, delight — captured without staging.',
        msIcon: 'emoji_emotions',
        color: '#f59e0b',
        group: 'creator',
        noAvatar: false,
        recommendedDuration: 8,
        recommendedFormat: '9:16',
        cameraSignature: 'Phone-native handheld at eye level. Slight unsteadiness — alive, not shaky. Rack focus from hands to face at the moment of recognition. Wide 14–24mm equivalent to stay close without distortion.',
        pacing: 'One beat every 2–3s. Slow build to the reveal. No cuts before 3s.',
        environmentDefault: 'Natural indoor daylight. Kitchen table, bedroom surface, or living room floor. No ring-light look. No studio backdrop. Imperfect is correct.',
        register: 'Warm, unpolished, peer-to-peer. Feels like a friend texting you a clip of something they just found.',
        cuts: 'Single continuous take preferred. No hard cuts.',
        forbiddenElements: ['studio backdrop', 'perfect symmetry', 'professional lighting rigs', 'ring light halo', 'supers text before 6s'],
        directorBrief: 'The camera arrives on a face — not a product. The hook is micro-expression: eyes widening, a small breath, fingers tightening around the packaging. The product enters the story through the person, not the other way around.',
    },

    {
        id: 'straight_to_camera',
        name: 'Straight to Camera',
        tagline: 'One person. One truth. No script.',
        threeWordCamera: 'Locked · Eye-level · Static',
        registerSummary: 'Conversational confidence. Talks to you, not at you.',
        description: 'Direct-to-camera. One presenter, one product, one honest thing to say. The camera never moves so nothing interrupts the connection.',
        msIcon: 'mic',
        color: '#3b82f6',
        group: 'creator',
        noAvatar: false,
        recommendedDuration: 10,
        recommendedFormat: '9:16',
        cameraSignature: 'Locked-off medium close-up at eye level. Slight head-room above. Telephoto 85–135mm to flatten the background. Camera does not move.',
        pacing: 'Continuous speech. No cut-aways. One subject, one position throughout.',
        environmentDefault: 'Soft window light from the side. Lived-in background — bookshelf, plant, or blurred room. Background soft from telephoto compression.',
        register: 'Conversational, confident, slightly informal. The presenter talks TO the viewer as if they are on a video call together.',
        cuts: 'No cuts. Single take from start to finish.',
        forbiddenElements: ['cutaway b-roll', 'product floating in space', 'motion graphics', 'voiceover without avatar on screen'],
        directorBrief: 'The presenter looks directly into the lens and says one true thing about the product. No demonstrations, no feature lists. Eye contact is the only technique. The camera never moves because nothing should interrupt the human-to-human connection.',
    },

    {
        id: 'product_drop',
        name: 'Product Drop',
        tagline: 'Reveal first. Explain never.',
        threeWordCamera: 'Push-in · Macro · Orbit',
        registerSummary: 'Confident and aspirational. The product speaks for itself.',
        description: 'A product-forward reveal. The hook is a fragment — a texture, an edge — then the full product in one deliberate camera move.',
        msIcon: 'bolt',
        color: '#8b5cf6',
        group: 'creator',
        noAvatar: false,
        recommendedDuration: 8,
        recommendedFormat: '9:16',
        cameraSignature: 'Dolly-in from wide to product close-up in first 2s. Then locked macro at macro focal length. One slow orbit — 45-degree arc maximum — around the product.',
        pacing: 'Hook within 1.5s. One action per 3s after. No rapid montage.',
        environmentDefault: 'Clean high-contrast surface — dark matte or light marble. Dramatic single-source sidelight from camera-left. No clutter in background.',
        register: 'Confident, aspirational, slightly premium. Less talk, more show.',
        cuts: 'Maximum 2 cuts. Product never leaves frame after it enters.',
        forbiddenElements: ['talking head before product reveal', 'cluttered background', 'more than 2 subjects', 'warm soft ambient light'],
        directorBrief: 'The video is already in progress when it starts — the product partially visible, already on the surface, already in the light. A single deliberate dolly-in or orbit completes the reveal without commentary. The absence of words is the statement.',
    },

    {
        id: 'day_in_the_life',
        name: 'Day in the Life',
        tagline: 'Product as part of a real routine.',
        threeWordCamera: 'Tracking · Handheld · Documentary',
        registerSummary: 'Aspirational but grounded. Vlog energy, not commercial.',
        description: 'The product appears naturally embedded in a real day. Grabbed from a bag, used at a desk, sipped before a commute. Life first, product second.',
        msIcon: 'schedule',
        color: '#10b981',
        group: 'creator',
        noAvatar: false,
        recommendedDuration: 10,
        recommendedFormat: '9:16',
        cameraSignature: 'Tracking shot follows the creator through space at standard 35–50mm equivalent. Camera moves WITH the subject — same direction, same pace — not at them.',
        pacing: 'Two scene moments within the duration. First and second half, each 4–5s. Implicit time-cut at midpoint — not a hard cut.',
        environmentDefault: 'Real-life settings — kitchen, gym, commute, desk. Natural ambient light. Slightly documentary, slightly imperfect.',
        register: 'Aspirational but grounded. Feels like a 10-second vlog snippet, not a scripted ad.',
        cuts: 'One implicit time-cut at midpoint. No more.',
        forbiddenElements: ['product on blank surface', 'obvious branding on every frame', 'scripted static poses', 'studio light'],
        directorBrief: 'The camera arrives on a creator already mid-activity. The product enters the story as something the creator reaches for naturally — not demonstrated, just used. The lifestyle sells the product by making it look necessary.',
    },

    {
        id: 'how_it_works',
        name: 'How It Works',
        tagline: 'Hands on. Step by step. Results shown.',
        threeWordCamera: 'Over-shoulder · Top-down · Hands',
        registerSummary: 'Instructional but energetic. "Here\'s exactly how."',
        description: 'A clean product demonstration. The viewer sees exactly how it works and what it does — no ambiguity, no skipped steps.',
        msIcon: 'touch_app',
        color: '#f97316',
        group: 'creator',
        noAvatar: false,
        recommendedDuration: 12,
        recommendedFormat: '9:16',
        cameraSignature: 'Over-the-shoulder or top-down stable shot. Telephoto 85mm equivalent for detail compression. Camera stays on the hands and the action — never the face.',
        pacing: '3–4 micro-steps, one per 2.5s. Quick but deliberate. No dead time between steps.',
        environmentDefault: 'Well-lit work surface. Natural light or soft controlled overhead. Clean, uncluttered. Product always visible.',
        register: 'Instructional, energetic. Imperative voice in dialogue if present — apply, hold, press, done.',
        cuts: '3–4 cuts, one per step. Each cut advances to the next step — not a new angle of the same step.',
        forbiddenElements: ['wide establishing shot held more than 2s', 'slow dramatic pacing', 'empty product shots without hands in frame'],
        directorBrief: 'The creator\'s hands do all the work. The camera watches the hands, never the face. Every cut advances to the next step of the process. The product is always central and always in use — never just displayed.',
    },

    {
        id: 'glow_up_story',
        name: 'Glow Up Story',
        tagline: 'Before the product. After the product.',
        threeWordCamera: 'Matching frames · Smash cut · Hold after',
        registerSummary: 'Slightly dramatic before, celebratory after. The contrast lands.',
        description: 'Two acts in one clip. The before state and the after state in matching frames — the contrast is the message.',
        msIcon: 'auto_awesome',
        color: '#ec4899',
        group: 'creator',
        noAvatar: false,
        recommendedDuration: 10,
        recommendedFormat: '9:16',
        cameraSignature: 'Identical angle, identical framing in before and after. Standard 35–50mm equivalent throughout. Smash cut at midpoint. No wipe, no dissolve.',
        pacing: 'Before: 4–5s. Smash cut. After: 4–5s. Equal weight on both sides.',
        environmentDefault: 'Consistent environment — same room, same light angle before and after. Credibility requires identical setup.',
        register: 'Slightly dramatic in the before, celebratory in the after. The smash cut is the punchline.',
        cuts: 'One structural smash cut at the midpoint. No other cuts.',
        forbiddenElements: ['mismatched angles between before and after', 'product demo in the middle of the arc', 'soft dissolve transition'],
        directorBrief: 'The structural discipline is everything. Before and after must be identical in framing. The product appears at the transition moment — held or placed — and then the after state holds without cutting away. The visual contrast does the persuading.',
    },

    {
        id: 'high_energy_cut',
        name: 'High Energy Cut',
        tagline: 'Fast. Impossible to scroll past.',
        threeWordCamera: 'Handheld · Whip-pan · Dutch',
        registerSummary: 'Kinetic, loud. Made for 2x playback.',
        description: 'Every frame hits hard. Fast cuts, dynamic angles, strong motion. The ad demands attention in the first half-second and never lets go.',
        msIcon: 'speed',
        color: '#ef4444',
        group: 'creator',
        noAvatar: false,
        recommendedDuration: 8,
        recommendedFormat: '9:16',
        cameraSignature: 'Handheld with intentional motion — whip-pans, dutch angles, push-ins. Speed ramp at the peak moment. Camera energy matches subject energy at all times.',
        pacing: 'Cut every 1.5–2s. 4–5 distinct clips within the duration. No single shot longer than 2.5s.',
        environmentDefault: 'Bold backgrounds. High contrast. Urban, gym, or high-energy lifestyle. No soft ambient light.',
        register: 'High-energy, kinetic, exciting. No slow moments. The product is always in motion.',
        cuts: '4–5 cuts. Every cut introduces a new angle or new energy beat.',
        forbiddenElements: ['static locked-off shots', 'slow dissolves', 'ambient calm', 'talking head', 'soft warm light'],
        directorBrief: 'The camera is already in motion when the ad starts — in medias res at full speed. Whip-pans transition between micro-moments. The product appears in every clip — held, used, moving. The pacing never drops below the energy of the opening frame.',
    },

    {
        id: 'crowd_pleaser',
        name: 'Crowd Pleaser',
        tagline: '"You need to know about this."',
        threeWordCamera: 'Intimate close-up · Lean-in · Drift',
        registerSummary: 'Conspiratorial and genuine. A friend pulling you aside.',
        description: 'The conspiratorial recommendation. Feels like a friend sharing a secret — one of the highest share-rate formats in social ads.',
        msIcon: 'groups',
        color: '#14b8a6',
        group: 'creator',
        noAvatar: false,
        recommendedDuration: 8,
        recommendedFormat: '9:16',
        cameraSignature: 'Handheld intimate close-up at eye level. Standard 35–50mm equivalent. Presenter leans toward camera at the opening. Natural slight drift throughout.',
        pacing: 'One idea per 2–3s. Urgency builds through the second half. Settles at the product moment.',
        environmentDefault: 'Natural light — whatever the real environment provides. Candid, not produced. Warm and intimate.',
        register: 'Conspiratorial, genuine, can\'t-contain-it energy. Not scripted. Not polished.',
        cuts: 'One or two cuts maximum. Continuous feel preferred.',
        forbiddenElements: ['wide establishing shot', 'studio backdrop', 'scripted-sounding delivery', 'matching studio background'],
        directorBrief: 'The creator leans toward the lens at the start — the visual equivalent of leaning across a table to share a secret. The product appears as the thing being shared. Energy peaks when the product is held close to camera.',
    },

    // ─── GROUP 2: Brand / Cinematic ───────────────────────────────────────────

    {
        id: 'hero_shot',
        name: 'Hero Shot',
        tagline: 'Your product as the only protagonist.',
        threeWordCamera: 'Slow orbit · Macro · Motivated',
        registerSummary: 'Ultra-premium silence. The product breathes.',
        description: 'Pure product cinematography. No presenter. The product moves and commands the frame. Like a luxury commercial for any category.',
        msIcon: 'movie',
        color: '#6366f1',
        group: 'brand',
        noAvatar: true,
        recommendedDuration: 8,
        recommendedFormat: '16:9',
        cameraSignature: 'Slow orbit around product at product height — 30-degree arc maximum. Macro push-in on surface texture. Telephoto 85–200mm for compression. Every camera move is motivated by a new product detail.',
        pacing: 'One move per 3–4s. Luxuriously slow. The product breathes between moves.',
        environmentDefault: 'Minimalist set. Single dramatic light source — hard sidelight or backlit silhouette. Deep black background. One surface element maximum.',
        register: 'Premium, aspirational, silent luxury. No dialogue. Every second of hold time communicates quality.',
        cuts: 'Maximum 2 cuts. Each cut reveals a new product angle — macro to orbit to full reveal.',
        forbiddenElements: ['presenter', 'dialogue', 'everyday lifestyle setting', 'warm casual ambient tones', 'busy or cluttered backgrounds'],
        directorBrief: 'The product is the only subject. The camera worships it — orbiting slowly, finding angles, lingering on material texture. Every camera move reveals something new about the product\'s physical form. Nothing else exists in this frame.',
    },

    {
        id: 'pain_to_relief',
        name: 'Pain → Relief',
        tagline: 'The problem is real. So is the fix.',
        threeWordCamera: 'Unflattering · Pivot · Warm eye-level',
        registerSummary: 'Empathetic first. Uplifting after. The viewer feels seen.',
        description: 'Two-act structure. Shows the exact moment of the problem, then the same person after the product resolves it.',
        msIcon: 'lightbulb',
        color: '#0ea5e9',
        group: 'brand',
        noAvatar: false,
        recommendedDuration: 10,
        recommendedFormat: '9:16',
        cameraSignature: 'Act 1: high-angle or low-angle to emphasise struggle — unflattering framing is intentional. Act 2: warm eye-level to show resolution. Camera angle shift marks the register change.',
        pacing: 'Act 1: fast and disruptive — 3s. One beat of stillness at pivot. Act 2: slower and resolved — 6–7s.',
        environmentDefault: 'Act 1: cluttered, harsh or poor light, stressful context. Act 2: same space made cleaner and warmer. Lighting shifts register between acts.',
        register: 'Empathetic in Act 1 — the viewer must feel seen. Uplifting in Act 2. No condescension.',
        cuts: 'One hard cut at the exact midpoint pivot. That cut is the entire emotional structure of the ad.',
        forbiddenElements: ['product appearing in Act 1', 'happy tone before the midpoint', 'abstract problem metaphors', 'overclaims not shown visually'],
        directorBrief: 'Act 1 shows the friction with physical specificity — not a metaphor, the actual thing going wrong. The camera angle is slightly unflattering here — it\'s intentional. The pivot cut is the beat of silence. Act 2 shows the same person after the product — same environment, measurably different.',
    },

    // ─── GROUP 3: Mantram Exclusive ───────────────────────────────────────────

    {
        id: 'pure_sensory',
        name: 'Pure Sensory',
        tagline: 'The beauty inside the everyday.',
        threeWordCamera: 'Macro · Slow-motion · Wide reveal',
        registerSummary: 'Sensory and clean. The physical qualities carry all the emotion.',
        description: 'Elevates everyday packaged goods into premium cinematic moments. A pour, a squeeze, a lather — each shot like a magazine cover.',
        msIcon: 'local_grocery_store',
        color: '#d97706',
        group: 'mantram-exclusive',
        noAvatar: true,
        recommendedDuration: 10,
        recommendedFormat: '16:9',
        cameraSignature: 'Macro focal length on product in use — surface detail fills frame. Slow-motion at the key sensory moment: the pour, the lather, the spread. Wide reveal at the end to show full product standing.',
        pacing: 'Slow macro (4s) → sensory peak in slow-motion (3s) → wide brand reveal (3s).',
        environmentDefault: 'Clean natural materials — dark wood, ceramic, water, fabric. Warm natural top light or window light from above. No plastic surfaces visible.',
        register: 'Sensory, aspirational, clean. The physical qualities of the product carry all the emotion. No words needed.',
        cuts: '2 cuts — macro to slow-motion peak, then to wide reveal.',
        forbiddenElements: ['dialogue', 'presenter talking to camera', 'cluttered environment', 'heavy logo before final frame', 'cold blue or harsh tones'],
        directorBrief: 'The camera finds the beauty inside the physical act of using the product. A pour, a squeeze, a lather — each shot as if for a food magazine. The product\'s sensory qualities — texture, colour, motion — are the entire narrative. Nothing is described that cannot be seen.',
    },

    {
        id: 'made_for_the_moment',
        name: 'Made for the Moment',
        tagline: 'The product belongs in this moment.',
        threeWordCamera: 'Warm handheld · Wide-to-close · Participatory',
        registerSummary: 'Warm, culturally specific, emotionally resonant.',
        description: 'Contextualises the product within a cultural festival or occasion. The product arrives at the emotional peak of the celebration.',
        msIcon: 'celebration',
        color: '#a855f7',
        group: 'mantram-exclusive',
        noAvatar: false,
        recommendedDuration: 10,
        recommendedFormat: '16:9',
        cameraSignature: 'Warm handheld moving through the celebration scene. Wide 14–24mm establishing, then close-in on the product moment at the emotional peak. Camera is participatory — inside the scene, not observing.',
        pacing: 'Wide establishing (2s) → intimate product moment at emotional peak (5s) → celebratory wide close (3s).',
        environmentDefault: 'Warm, festive, culturally resonant and specific. Candles, lights, fabric, colour specific to the occasion. Practical light sources from the occasion itself — lamps, diyas, fairy lights.',
        register: 'Warm, emotionally resonant, celebratory. Nostalgic without being saccharine. Culturally specific, never generic or multicultural-bland.',
        cuts: '2 cuts — establishing to intimate product moment, intimate to celebratory close.',
        forbiddenElements: ['generic stock footage energy', 'culturally neutral setting', 'product-only shots without occasion context', 'cold light or blue tones'],
        directorBrief: 'The product is not advertised — it arrives as the natural object for this moment. The camera is warm and participatory. The product placement at the emotional peak is slow and deliberate, as if the product has always been part of this ritual.',
    },

    {
        id: 'the_transformation',
        name: 'The Transformation',
        tagline: 'The evidence speaks.',
        threeWordCamera: 'Identical frames · Hard cut · Hold after',
        registerSummary: 'Factual and confident. The visual evidence persuades.',
        description: 'Before and after in identical framing — same distance, same angle, same light direction. The transformation is unmissable.',
        msIcon: 'compare',
        color: '#06b6d4',
        group: 'mantram-exclusive',
        noAvatar: false,
        recommendedDuration: 10,
        recommendedFormat: '9:16',
        cameraSignature: 'Identical framing in before and after — same distance, same angle, standard 35–50mm. Hard cut at the reveal. Camera never moves throughout.',
        pacing: 'Before state: 3s. Product enters: 2s. After state: 5s. After state holds and breathes — let it land.',
        environmentDefault: 'Controlled and consistent. Both states must feel like the same location at the same time of day. Clean, undistracting background that does not change.',
        register: 'Factual, confident, results-focused. The visual evidence does all the persuading. No emotional manipulation.',
        cuts: 'One structural hard cut at the transformation reveal. Camera setup never changes.',
        forbiddenElements: ['mismatched camera angles', 'CGI overlay effects', 'soft or flattering before state that undermines credibility', 'performance claims not shown visually'],
        directorBrief: 'Credibility is the entire strategy. The camera setup is literally identical — same angle, same light direction — in before and after. The result must look real. Any sign of over-production destroys the trust the format is designed to build.',
    },

];

// ── Lookup helpers ─────────────────────────────────────────────────────────────

export function getPreset(id) {
    return Q_ADS_PRESETS.find(p => p.id === id) || null;
}

export function getPresetsForFrontend() {
    return Q_ADS_PRESETS.map(p => ({
        id: p.id,
        name: p.name,
        tagline: p.tagline,
        threeWordCamera: p.threeWordCamera,
        registerSummary: p.registerSummary,
        description: p.description,
        msIcon: p.msIcon,
        color: p.color,
        group: p.group,
        noAvatar: p.noAvatar,
        recommendedDuration: p.recommendedDuration,
        recommendedFormat: p.recommendedFormat,
    }));
}

// Complete antislop list — all output is rejected if any of these appear
export const ANTISLOP_BANNED_WORDS = [
    'breathtaking', 'stunning', 'captivating', 'mesmerizing', 'awe-inspiring',
    'masterfully', 'meticulously', 'exquisitely', 'beautifully crafted',
    'cinematic masterpiece', 'visual feast', 'a symphony of', 'seamlessly',
    'effortlessly', 'flawlessly', 'cutting-edge', 'state-of-the-art', 'next-level',
    'rich tapestry', 'vibrant tapestry', 'kaleidoscope of', 'elevate', 'unlock',
    'unleash', 'harness', 'groundbreaking', 'a testament to', 'speaks volumes',
    'resonates deeply', 'game-changer', 'revolutionary', 'redefine', 'reimagine',
    'dynamic', 'vibrant', 'innovative', 'transformative', 'tapestry', 'enigma',
    'transcendent', 'ethereal', 'luminous', 'symphony', 'delve', 'timeless',
    'bespoke', 'curated', 'nestled', 'bustling', 'whispering', 'heartwarming',
    'soulful', 'cinematic journey', 'magical',
];

// Age-blind rule — banned age descriptors for character descriptions
export const AGEBLIND_BANNED_WORDS = [
    'young', 'old', 'teen', 'teenager', 'elderly', 'aged', 'middle-aged',
    'boy', 'girl', 'child', 'children', 'adult', 'senior', 'youthful',
    'juvenile', 'mature', 'older', 'younger', 'little', 'kid', 'baby',
];
