export const IMAGE_MODEL_RATES = [
    { id: 'nano-banana-2-lite-edit-dev', name: 'Nano Banana 2 Lite Edit Developer', provider: 'google', category: 'Image-to-Image', usdPerPic: 0.028 },
    { id: 'nano-banana-2-lite-t2i-dev', name: 'Nano Banana 2 Lite Text-to-Image Developer', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.028 },
    { id: 'nano-banana-2-lite-edit', name: 'Nano Banana 2 Lite Edit', provider: 'google', category: 'Image-to-Image', usdPerPic: 0.04 },
    { id: 'nano-banana-2-lite-t2i', name: 'Nano Banana 2 Lite Text-to-image', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.04 },
    { id: 'mai-image-2.5-flash-t2i', name: 'MAI-Image-2.5-Flash Text-to-image', provider: 'microsoft', category: 'Text-to-Image', usdPerPic: 0.03 },
    { id: 'mai-image-2.5-edit', name: 'MAI-Image-2.5 Edit', provider: 'microsoft', category: 'Image-to-Image', usdPerPic: 0.058 },
    { id: 'mai-image-2.5-t2i', name: 'MAI-Image-2.5 Text-to-image', provider: 'microsoft', category: 'Text-to-Image', usdPerPic: 0.05 },
    { id: 'youchuan-8.1-remove-bg', name: 'Youchuan V8.1 Remove Background', provider: 'piapi', category: 'Image-to-Image', usdPerPic: 0.086 },
    { id: 'youchuan-8.1-style-transfer', name: 'Youchuan V8.1 Style Transfer', provider: 'piapi', category: 'Image-to-Image', usdPerPic: 0.129 },
    { id: 'youchuan-8.1-blend', name: 'Youchuan V8.1 Blend', provider: 'piapi', category: 'Image-to-Image', usdPerPic: 0.086 },
    { id: 'youchuan-8.1-i2i', name: 'Youchuan V8.1 Image-to-Image', provider: 'piapi', category: 'Image-to-Image', usdPerPic: 0.086 },
    { id: 'youchuan-8.1-t2i', name: 'Youchuan V8.1 Text-to-Image', provider: 'piapi', category: 'Text-to-Image', usdPerPic: 0.086 },
    { id: 'nano-banana-2-ref-image', name: 'Nano Banana 2 Reference to Image', provider: 'google', category: 'Image-to-Image', usdPerPic: 0.08 },
    { id: 'nano-banana-2-ref-image-dev', name: 'Nano Banana 2 Reference to Image Developer', provider: 'google', category: 'Image-to-Image', usdPerPic: 0.04 },
    { id: 'grok-imagine-quality-t2i', name: 'Grok Imagine Image Quality Text-to-Image', provider: 'grok', category: 'Text-to-Image', usdPerPic: 0.05 },
    { id: 'grok-imagine-quality-edit', name: 'Grok Imagine Image Quality Edit', provider: 'grok', category: 'Image-to-Image', usdPerPic: 0.05 },
    { id: 'openai-gpt-image-2-t2i', name: 'Openai GPT Image 2 Text-to-Image', provider: 'openai', category: 'Text-to-Image', usdPerPic: 0.009 },
    { id: 'openai-gpt-image-2-edit', name: 'Openai GPT Image 2 Edit', provider: 'openai', category: 'Image-to-Image', usdPerPic: 0.01 },
    { id: 'baidu-ernie-turbo-t2i', name: 'Baidu ERNIE Image Turbo Text-to-image', provider: 'baidu', category: 'Text-to-Image', usdPerPic: 0.0 },
    { id: 'wan-2.7-t2i', name: 'Wan-2.7 Text-to-image', provider: 'laozhang', category: 'Text-to-Image', usdPerPic: 0.03 },
    { id: 'wan-2.7-i2i', name: 'Wan-2.7 Image-to-image', provider: 'laozhang', category: 'Image-to-Image', usdPerPic: 0.03 },
    { id: 'wan-2.7-pro-t2i', name: 'Wan-2.7 Pro Text-to-image', provider: 'laozhang', category: 'Text-to-Image', usdPerPic: 0.075 },
    { id: 'wan-2.7-pro-i2i', name: 'Wan-2.7 Pro Image-to-image', provider: 'laozhang', category: 'Image-to-Image', usdPerPic: 0.075 },
    { id: 'nano-banana-2-t2i-dev', name: 'Nano Banana 2 Text-to-Image Developer', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.04 },
    { id: 'nano-banana-2-t2i', name: 'Nano Banana 2 Text-to-Image', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.08 },
    { id: 'nano-banana-2-edit-dev', name: 'Nano Banana 2 Edit Developer', provider: 'google', category: 'Image-to-Image', usdPerPic: 0.04 },
    { id: 'nano-banana-2-edit', name: 'Nano Banana 2 Edit', provider: 'google', category: 'Image-to-Image', usdPerPic: 0.08 },
    { id: 'qwen-image-2.0-t2i', name: 'Qwen Image 2.0 Text-to-image', provider: 'qwen', category: 'Text-to-Image', usdPerPic: 0.028 },
    { id: 'qwen-image-2.0-edit', name: 'Qwen Image 2.0 Edit', provider: 'qwen', category: 'Image-to-Image', usdPerPic: 0.028 },
    { id: 'qwen-image-2.0-pro-edit', name: 'Qwen Image 2.0 Pro Edit', provider: 'qwen', category: 'Image-to-Image', usdPerPic: 0.06 },
    { id: 'qwen-image-2.0-pro-t2i', name: 'Qwen Image 2.0 Pro Text-to-image', provider: 'qwen', category: 'Text-to-Image', usdPerPic: 0.06 },
    { id: 'seedream-5.0-lite-edit-seq', name: 'Seedream v5.0 Lite Edit Sequential', provider: 'bytedance', category: 'Image-to-Image', usdPerPic: 0.032 },
    { id: 'seedream-5.0-lite-seq', name: 'Seedream v5.0 Lite Sequential', provider: 'bytedance', category: 'Text-to-Image', usdPerPic: 0.032 },
    { id: 'seedream-5.0-lite-edit', name: 'Seedream v5.0 Lite Edit', provider: 'bytedance', category: 'Image-to-Image', usdPerPic: 0.032 },
    { id: 'seedream-5.0-lite', name: 'Seedream v5.0 Lite', provider: 'bytedance', category: 'Text-to-Image', usdPerPic: 0.032 },
    { id: 'openai-gpt-image-1.5-t2i', name: 'Openai GPT Image-1.5 Text-to-image', provider: 'openai', category: 'Text-to-Image', usdPerPic: 0.008 },
    { id: 'openai-gpt-image-1.5-edit', name: 'Openai GPT Image-1.5 Edit', provider: 'openai', category: 'Image-to-Image', usdPerPic: 0.008 },
    { id: 'qwen-image-edit-plus-20251215', name: 'Qwen-Image Edit Plus 20251215', provider: 'qwen', category: 'Image-to-Image', usdPerPic: 0.021 },
    { id: 'wan-2.6-i2i', name: 'Wan-2.6 Image-to-image', provider: 'laozhang', category: 'Image-to-Image', usdPerPic: 0.021 },
    { id: 'z-image-turbo', name: 'Z-Image Turbo', provider: 'laozhang', category: 'Text-to-Image', usdPerPic: 0.005 },
    { id: 'openai-gpt-image-1-t2i', name: 'Openai GPT Image-1 Text-to-image', provider: 'openai', category: 'Text-to-Image', usdPerPic: 0.009 },
    { id: 'openai-gpt-image-1-edit', name: 'Openai GPT Image-1 Edit', provider: 'openai', category: 'Image-to-Image', usdPerPic: 0.009 },
    { id: 'openai-gpt-image-1-mini-t2i', name: 'Openai GPT Image-1 Mini Text-to-image', provider: 'openai', category: 'Text-to-Image', usdPerPic: 0.004 },
    { id: 'openai-gpt-image-1-mini-edit', name: 'Openai GPT Image-1 Mini Edit', provider: 'openai', category: 'Image-to-Image', usdPerPic: 0.004 },
    { id: 'seedream-4.5', name: 'Seedream v4.5', provider: 'bytedance', category: 'Text-to-Image', usdPerPic: 0.036 },
    { id: 'seedream-4.5-edit', name: 'Seedream v4.5 Edit', provider: 'bytedance', category: 'Image-to-Image', usdPerPic: 0.036 },
    { id: 'seedream-4.5-seq', name: 'Seedream v4.5 Sequential', provider: 'bytedance', category: 'Text-to-Image', usdPerPic: 0.036 },
    { id: 'seedream-4.5-edit-seq', name: 'Seedream v4.5 Edit Sequential', provider: 'bytedance', category: 'Image-to-Image', usdPerPic: 0.036 },
    { id: 'qwen-image-edit-base', name: 'Qwen Image Edit', provider: 'qwen', category: 'Image-to-Image', usdPerPic: 0.032 },
    { id: 'nano-banana-pro-t2i-ultra', name: 'Nano Banana Pro Text-to-image Ultra', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.15 },
    { id: 'nano-banana-pro-edit-ultra', name: 'Nano Banana Pro Edit Ultra', provider: 'google', category: 'Image-to-Image', usdPerPic: 0.15 },
    { id: 'nano-banana-pro-t2i', name: 'Nano Banana Pro Text-to-image', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.14 },
    { id: 'qwen-image-t2i-max', name: 'Qwen-Image Text-to-image Max', provider: 'qwen', category: 'Text-to-Image', usdPerPic: 0.052 },
    { id: 'qwen-image-t2i-plus', name: 'Qwen-Image Text-to-image Plus', provider: 'qwen', category: 'Text-to-Image', usdPerPic: 0.021 },
    { id: 'nano-banana-pro-edit', name: 'Nano Banana Pro Edit', provider: 'google', category: 'Image-to-Image', usdPerPic: 0.14 },
    { id: 'grok-imagine-image-edit', name: 'Grok Imagine Image Edit', provider: 'grok', category: 'Image-to-Image', usdPerPic: 0.02 },
    { id: 'grok-imagine-image-t2i', name: 'Grok Imagine Image Text-to-Image', provider: 'grok', category: 'Text-to-Image', usdPerPic: 0.02 },
    { id: 'gpt-image-2-dev-edit', name: 'GPT Image 2 Developer Edit', provider: 'openai', category: 'Image-to-Image', usdPerPic: 0.005 },
    { id: 'wan-2.5-image-edit', name: 'Wan-2.5 Image Edit', provider: 'laozhang', category: 'Image-to-Image', usdPerPic: 0.021 },
    { id: 'gpt-image-2-dev-t2i', name: 'GPT Image 2 Developer Text-to-Image', provider: 'openai', category: 'Text-to-Image', usdPerPic: 0.004 },
    { id: 'wan-2.5-t2i', name: 'Wan-2.5 Text-to-image', provider: 'laozhang', category: 'Text-to-Image', usdPerPic: 0.021 },
    { id: 'seedream-v4', name: 'Seedream v4', provider: 'bytedance', category: 'Text-to-Image', usdPerPic: 0.027 },
    { id: 'seedream-v4-seq', name: 'Seedream v4 Sequential', provider: 'bytedance', category: 'Text-to-Image', usdPerPic: 0.027 },
    { id: 'nano-banana-pro-t2i-dev', name: 'Nano Banana Pro Text-to-image Developer', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.07 },
    { id: 'nano-banana-t2i-dev', name: 'Nano Banana Text-to-image Developer', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.019 },
    { id: 'seedream-v4-edit', name: 'Seedream v4 Edit', provider: 'bytedance', category: 'Image-to-Image', usdPerPic: 0.027 },
    { id: 'qwen-image-edit-std', name: 'Qwen-Image Edit', provider: 'qwen', category: 'Image-to-Image', usdPerPic: 0.032 },
    { id: 'qwen-image-edit-plus', name: 'Qwen-Image Edit Plus', provider: 'qwen', category: 'Image-to-Image', usdPerPic: 0.021 },
    { id: 'wan-2.6-t2i', name: 'Wan-2.6 Text-to-image', provider: 'laozhang', category: 'Text-to-Image', usdPerPic: 0.021 },
    { id: 'nano-banana-pro-edit-dev', name: 'Nano Banana Pro Edit Developer', provider: 'google', category: 'Image-to-Image', usdPerPic: 0.07 },
    { id: 'nano-banana-edit-dev', name: 'Nano Banana Edit Developer', provider: 'google', category: 'Image-to-Image', usdPerPic: 0.019 },
    { id: 'seedream-v4-edit-seq', name: 'Seedream v4 Edit Sequential', provider: 'bytedance', category: 'Image-to-Image', usdPerPic: 0.027 },
    { id: 'nano-banana-t2i', name: 'Nano Banana Text-to-image', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.038 },
    { id: 'nano-banana-edit', name: 'Nano Banana Edit', provider: 'google', category: 'Image-to-Image', usdPerPic: 0.038 },
    { id: 'imagen3', name: 'Imagen3', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.04 },
    { id: 'imagen3-fast', name: 'Image3 Fast', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.02 },
    { id: 'qwen-image-t2i', name: 'Qwen Image Text-to-image', provider: 'qwen', category: 'Text-to-Image', usdPerPic: 0.024 },
    { id: 'imagen4-fast', name: 'Imagen4 Fast', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.02 },
    { id: 'flux-dev', name: 'Flux Dev', provider: 'fal', category: 'Text-to-Image', usdPerPic: 0.012 },
    { id: 'flux-kontext-dev', name: 'Flux Kontext Dev', provider: 'fal', category: 'Image-to-Image', usdPerPic: 0.025 },
    { id: 'imagen4-ultra', name: 'Imagen4 Ultra', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.06 },
    { id: 'imagen4', name: 'Imagen4', provider: 'google', category: 'Text-to-Image', usdPerPic: 0.04 },
    { id: 'flux-kontext-dev-lora', name: 'Flux Kontext Dev Lora', provider: 'fal', category: 'Image-to-Image', usdPerPic: 0.03 },
    { id: 'flux-schnell', name: 'Flux Schnell', provider: 'fal', category: 'Text-to-Image', usdPerPic: 0.003 },
    { id: 'mai-image-2.5-flash-edit', name: 'MAI-Image-2.5-Flash Edit', provider: 'microsoft', category: 'Image-to-Image', usdPerPic: 0.038 },
    { id: 'flux.2-flex-edit', name: 'FLUX.2 Flex Edit', provider: 'fal', category: 'Image-to-Image', usdPerPic: 0.05 },
    { id: 'flux.2-flex-t2i', name: 'FLUX.2 Flex Text-to-image', provider: 'fal', category: 'Text-to-Image', usdPerPic: 0.05 },
    { id: 'flux.2-pro-edit', name: 'FLUX.2 Pro Edit', provider: 'fal', category: 'Image-to-Image', usdPerPic: 0.03 },
    { id: 'flux.2-pro-t2i', name: 'FLUX.2 Pro Text-to-image', provider: 'fal', category: 'Text-to-Image', usdPerPic: 0.03 },
    { id: 'flux-dev-lora', name: 'Flux Dev Lora', provider: 'fal', category: 'Text-to-Image', usdPerPic: 0.015 }
];
