export const VIDEO_MODEL_RATES = [
    { id: 'seedance-2.0-mini-r2v', name: 'Seedance 2.0 Mini Reference-to-Video', provider: 'atlascloud', category: 'Reference-to-Video', usdPerSec: 0.045 },
    { id: 'seedance-2.0-mini-i2v', name: 'Seedance 2.0 Mini Image-to-Video', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.045 },
    { id: 'seedance-2.0-mini-t2v', name: 'Seedance 2.0 Mini Text-to-Video', provider: 'atlascloud', category: 'Text-to-Video', usdPerSec: 0.045 },
    { id: 'happyhorse-1.1-t2v', name: 'HappyHorse-1.1 Text-to-video', provider: 'atlascloud', category: 'Text-to-Video', usdPerSec: 0.14 },
    { id: 'happyhorse-1.1-i2v', name: 'HappyHorse-1.1 Image-to-video', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.14 },
    { id: 'gemini-omni-flash-i2v', name: 'Gemini Omni Flash Image-to-Video', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.13 },
    { id: 'gemini-omni-flash-edit', name: 'Gemini Omni Flash Video Edit', provider: 'atlascloud', category: 'Video-Edit', usdPerSec: 0.14 },
    { id: 'gemini-omni-flash-t2v', name: 'Gemini Omni Flash Text-to-Video', provider: 'atlascloud', category: 'Text-to-Video', usdPerSec: 0.125 },
    { id: 'gemini-omni-flash-r2v-dev', name: 'Gemini Omni Flash Reference-to-Video Developer', provider: 'atlascloud', category: 'Reference-to-Video', usdPerSec: 0.12 },
    { id: 'avatar-omni-human-1.5', name: 'Avatar Omni Human 1.5', provider: 'atlascloud', category: 'Audio-to-Video', usdPerSec: 0.06 },
    { id: 'kling-3.0-turbo-i2v', name: 'Kling V3.0 Turbo Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.095 },
    { id: 'kling-3.0-turbo-t2v', name: 'Kling V3.0 Turbo Text-to-Video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.095 },
    { id: 'kling-o3-4k-i2v', name: 'Kling Video O3 4K Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.357 },
    { id: 'kling-o3-4k-t2v', name: 'Kling Video O3 4K Text-to-Video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.357 },
    { id: 'youchuan-8.1', name: 'Youchuan V8.1 Image-to-Video', provider: 'piapi', category: 'Image-to-Video', usdPerSec: 0.086 },
    { id: 'grok-imagine-1.5-i2v', name: 'Grok Imagine Video v1.5 Image-to-Video', provider: 'grok', category: 'Image-to-Video', usdPerSec: 0.08 },
    { id: 'gemini-omni-flash-i2v-dev', name: 'Gemini Omni Flash Image-to-Video Developer', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.112 },
    { id: 'gemini-omni-flash-t2v-dev', name: 'Gemini Omni Flash Text-to-Video Developer', provider: 'atlascloud', category: 'Text-to-Video', usdPerSec: 0.112 },
    { id: 'happyhorse-1.0-t2v', name: 'HappyHorse-1.0 Text-to-video', provider: 'atlascloud', category: 'Text-to-Video', usdPerSec: 0.14 },
    { id: 'happyhorse-1.0-i2v', name: 'HappyHorse-1.0 Image-to-video', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.14 },
    { id: 'happyhorse-1.0-edit', name: 'HappyHorse-1.0 Video-edit', provider: 'atlascloud', category: 'Video-Edit', usdPerSec: 0.14 },
    { id: 'seedance-2.0-t2v', name: 'Seedance 2.0 Text-to-Video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.09 },
    { id: 'seedance-2.0-i2v', name: 'Seedance 2.0 Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.09 },
    { id: 'seedance-2.0-r2v', name: 'Seedance 2.0 Reference-to-Video', provider: 'laozhang', category: 'Reference-to-Video', usdPerSec: 0.09 },
    { id: 'seedance-2.0-fast-t2v', name: 'Seedance 2.0 Fast Text-to-Video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.072 },
    { id: 'seedance-2.0-fast-i2v', name: 'Seedance 2.0 Fast Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.072 },
    { id: 'seedance-2.0-fast-r2v', name: 'Seedance 2.0 Fast Reference-to-Video', provider: 'laozhang', category: 'Reference-to-Video', usdPerSec: 0.072 },
    { id: 'wan-2.7-t2v', name: 'Wan-2.7 Text-to-video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.10 },
    { id: 'wan-2.7-i2v', name: 'Wan-2.7 Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.10 },
    { id: 'wan-2.7-r2v', name: 'Wan-2.7 Reference-to-video', provider: 'laozhang', category: 'Reference-to-Video', usdPerSec: 0.10 },
    { id: 'wan-2.7-edit', name: 'Wan-2.7 Video-edit', provider: 'laozhang', category: 'Video-Edit', usdPerSec: 0.10 },
    { id: 'veo-3.1-lite-t2v', name: 'Veo 3.1 Lite Text-to-video', provider: 'atlascloud', category: 'Text-to-Video', usdPerSec: 0.05 },
    { id: 'veo-3.1-lite-start-end', name: 'Veo 3.1 Lite Start-End Frame to Video', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.05 },
    { id: 'veo-3.1-lite-i2v', name: 'Veo 3.1 Lite Image-to-video', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.05 },
    { id: 'vidu-q3-mix-r2v', name: 'Vidu Q3-Mix Reference to Video', provider: 'laozhang', category: 'Reference-to-Video', usdPerSec: 0.106 },
    { id: 'vidu-q3-r2v', name: 'Vidu Q3 Reference to Video', provider: 'laozhang', category: 'Reference-to-Video', usdPerSec: 0.042 },
    { id: 'wan-2.2-turbo-spicy-lora', name: 'Wan-2.2-turbo-spicy Image-to-video Lora', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.026 },
    { id: 'wan-2.2-turbo-spicy-i2v', name: 'Wan-2.2-turbo-spicy Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.02 },
    { id: 'veo-3.1-fast-i2v', name: 'Veo3.1 Fast Image-to-video', provider: 'fal', category: 'Image-to-Video', usdPerSec: 0.08 },
    { id: 'veo-3.1-fast-t2v', name: 'Veo3.1 Fast Text-to-video', provider: 'fal', category: 'Text-to-Video', usdPerSec: 0.08 },
    { id: 'veo-3.1-i2v', name: 'Veo3.1 Image-to-video', provider: 'fal', category: 'Image-to-Video', usdPerSec: 0.20 },
    { id: 'veo-3.1-r2v', name: 'Veo3.1 Reference-to-video', provider: 'fal', category: 'Reference-to-Video', usdPerSec: 0.20 },
    { id: 'veo-3.1-t2v', name: 'Veo3.1 Text-to-video', provider: 'fal', category: 'Text-to-Video', usdPerSec: 0.20 },
    { id: 'grok-imagine-t2v', name: 'Grok Imagine Video Text-to-Video', provider: 'grok', category: 'Text-to-Video', usdPerSec: 0.05 },
    { id: 'grok-imagine-i2v', name: 'Grok Imagine Video Image-to-Video', provider: 'grok', category: 'Image-to-Video', usdPerSec: 0.05 },
    { id: 'grok-imagine-r2v', name: 'Grok Imagine Video Reference-to-Video', provider: 'grok', category: 'Reference-to-Video', usdPerSec: 0.05 },
    { id: 'grok-imagine-extend', name: 'Grok Imagine Video Extend', provider: 'grok', category: 'Video-Extension', usdPerSec: 0.07 },
    { id: 'grok-imagine-edit', name: 'Grok Imagine Video Edit', provider: 'grok', category: 'Video-Edit', usdPerSec: 0.07 },
    { id: 'wan-2.2-turbo-i2v', name: 'Wan 2.2 Turbo Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.02 },
    { id: 'wan-2.2-turbo-infinite', name: 'Wan 2.2 Turbo Infinite Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.02 },
    { id: 'wan-2.2-turbo-infinite-lora', name: 'Wan 2.2 Turbo Infinite Image-to-Video LoRA', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.026 },
    { id: 'wan-2.2-turbo-spicy-infinite', name: 'Wan 2.2 Turbo Spicy Infinite Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.02 },
    { id: 'wan-2.2-turbo-spicy-infinite-lora', name: 'Wan 2.2 Turbo Spicy Infinite Image-to-Video LoRA', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.026 },
    { id: 'wan-2.2-i2v', name: 'Wan-2.2 Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.03 },
    { id: 'wan-2.2-i2v-lora', name: 'Wan-2.2 Image-to-video Lora', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.04 },
    { id: 'wan-2.2-spicy-i2v-lora', name: 'Wan-2.2-spicy Image-to-video Lora', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.04 },
    { id: 'wan-2.2-spicy-i2v', name: 'Wan-2.2-spicy Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.03 },
    { id: 'video-upscaler', name: 'Video Upscaler', provider: 'atlascloud', category: 'Video-Upscale', usdPerSec: 0.018 },
    { id: 'vidu-q3-pro-start-end', name: 'Vidu Q3-Pro Start-end-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.042 },
    { id: 'vidu-q3-turbo-i2v', name: 'Vidu Q3-Turbo Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.034 },
    { id: 'vidu-q3-turbo-start-end', name: 'Vidu Q3-Turbo Start-end-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.034 },
    { id: 'vidu-q3-turbo-t2v', name: 'Vidu Q3-Turbo Text-to-video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.034 },
    { id: 'kling-v3.0-4k-i2v', name: 'Kling v3.0 4K Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.357 },
    { id: 'kling-v3.0-std-i2v', name: 'Kling v3.0 Std Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.071 },
    { id: 'kling-v3.0-pro-i2v', name: 'Kling v3.0 Pro Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.095 },
    { id: 'kling-v3.0-pro-t2v', name: 'Kling v3.0 Pro Text-to-Video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.095 },
    { id: 'kling-v3.0-4k-t2v', name: 'Kling v3.0 4K Text-to-Video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.357 },
    { id: 'kling-v3.0-std-t2v', name: 'Kling v3.0 Std Text-to-Video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.071 },
    { id: 'vidu-q3-pro-i2v', name: 'Vidu Q3-Pro Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.042 },
    { id: 'vidu-q3-pro-t2v', name: 'Vidu Q3-Pro Text-to-video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.042 },
    { id: 'kling-2.6-pro-avatar', name: 'Kling v2.6 Pro Avatar', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.095 },
    { id: 'kling-2.6-std-avatar', name: 'Kling v2.6 Std Avatar', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.048 },
    { id: 'kling-2.6-pro-motion', name: 'Kling v2.6 Pro Motion Control', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.095 },
    { id: 'kling-2.6-std-motion', name: 'Kling v2.6 Std Motion Control', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.06 },
    { id: 'wan-2.6-i2v-flash', name: 'Wan-2.6 Image-to-video Flash', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.018 },
    { id: 'seedance-1.5-pro-i2v', name: 'Seedance v1.5 Pro Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.047 },
    { id: 'seedance-1.5-pro-t2v', name: 'Seedance v1.5 Pro Text-to-Video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.047 },
    { id: 'seedance-1.5-pro-i2v-fast', name: 'Seedance v1.5 Pro Image-to-Video Fast', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.018 },
    { id: 'wan-2.6-i2v', name: 'Wan-2.6 Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.07 },
    { id: 'wan-2.6-v2v', name: 'Wan-2.6 Video-to-video', provider: 'laozhang', category: 'Video-to-Video', usdPerSec: 0.07 },
    { id: 'wan-2.6-t2v', name: 'Wan-2.6 Text-to-video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.07 },
    { id: 'kling-o3-pro-edit', name: 'Kling Video O3 Pro Video-Edit', provider: 'laozhang', category: 'Video-Edit', usdPerSec: 0.143 },
    { id: 'kling-o3-pro-r2v', name: 'Kling Video O3 Pro Reference-to-Video', provider: 'laozhang', category: 'Reference-to-Video', usdPerSec: 0.095 },
    { id: 'kling-o3-pro-i2v', name: 'Kling Video O3 Pro Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.095 },
    { id: 'kling-o3-pro-t2v', name: 'Kling Video O3 Pro Text-to-Video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.095 },
    { id: 'seedance-1.5-pro-fast-t2v', name: 'Seedance v1.5 Pro Text-to-Video Fast', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.018 },
    { id: 'kling-2.6-pro-t2v', name: 'Kling v2.6 Pro Text-to-Video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.06 },
    { id: 'kling-2.6-pro-i2v', name: 'Kling v2.6 Pro Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.06 },
    { id: 'kling-o3-std-edit', name: 'Kling Video O3 Std Video-Edit', provider: 'laozhang', category: 'Video-Edit', usdPerSec: 0.107 },
    { id: 'kling-o3-std-r2v', name: 'Kling Video O3 Std Reference-to-Video', provider: 'laozhang', category: 'Reference-to-Video', usdPerSec: 0.071 },
    { id: 'kling-o3-std-i2v', name: 'Kling Video O3 Std Image-to-Video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.071 },
    { id: 'kling-o3-std-t2v', name: 'Kling Video O3 Std Text-to-Video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.071 },
    { id: 'kling-o1-i2v', name: 'Kling Video O1 Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.095 },
    { id: 'kling-o1-t2v', name: 'Kling Video O1 Text-to-video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.095 },
    { id: 'pixverse-v6-extend', name: 'Pixverse v6 Video-Extend', provider: 'atlascloud', category: 'Video-Extension', usdPerSec: 0.025 },
    { id: 'pixverse-c1-i2v', name: 'Pixverse c1 Image-to-Video', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.03 },
    { id: 'pixverse-c1-start-end', name: 'Pixverse c1 Start-End-to-Video', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.03 },
    { id: 'pixverse-v6-t2v', name: 'Pixverse v6 Text-to-Video', provider: 'atlascloud', category: 'Text-to-Video', usdPerSec: 0.025 },
    { id: 'pixverse-v6-i2v', name: 'Pixverse v6 Image-to-Video', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.025 },
    { id: 'pixverse-v6-start-end', name: 'Pixverse v6 Start-End-to-Video', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.025 },
    { id: 'pixverse-c1-t2v', name: 'Pixverse c1 Text-to-Video', provider: 'atlascloud', category: 'Text-to-Video', usdPerSec: 0.03 },
    { id: 'seedance-1.5-pro-spicy', name: 'Seedance v1.5 Pro Image-to-Video Spicy', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.049 },
    { id: 'infinitetalk', name: 'InfiniteTalk', provider: 'piapi', category: 'Audio-to-Video', usdPerSec: 0.03 },
    { id: 'wan-2.5-extend', name: 'Wan-2.5 Video Extend', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.052 },
    { id: 'hailuo-2.3-t2v-std', name: 'Hailuo-2.3 t2v Standard', provider: 'hailuo', category: 'Text-to-Video', usdPerSec: 0.28 },
    { id: 'hailuo-2.3-t2v-pro', name: 'Hailuo-2.3 t2v Pro', provider: 'hailuo', category: 'Text-to-Video', usdPerSec: 0.49 },
    { id: 'hailuo-2.3-i2v-std', name: 'Hailuo-2.3 i2v Standard', provider: 'hailuo', category: 'Image-to-Video', usdPerSec: 0.28 },
    { id: 'hailuo-2.3-i2v-pro', name: 'Hailuo-2.3 i2v Pro', provider: 'hailuo', category: 'Image-to-Video', usdPerSec: 0.49 },
    { id: 'hailuo-2.3-fast', name: 'Hailuo-2.3 Fast', provider: 'hailuo', category: 'Image-to-Video', usdPerSec: 0.19 },
    { id: 'seedance-v1-pro-fast-t2v', name: 'Seedance v1 Pro Fast Text-to-video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.009 },
    { id: 'seedance-v1-pro-fast-i2v', name: 'Seedance v1 Pro Fast Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.009 },
    { id: 'kling-2.5-turbo-pro-t2v', name: 'Kling v2.5 Turbo Pro Text-to-video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.06 },
    { id: 'kling-2.5-turbo-pro-i2v', name: 'Kling v2.5 Turbo Pro Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.06 },
    { id: 'kling-2.1-i2v-pro-start-end', name: 'Kling v2.1 i2v Pro Start-end-frame', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.083 },
    { id: 'kling-1.6-multi-i2v-pro', name: 'Kling v1.6 Multi i2v Pro', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.083 },
    { id: 'kling-1.6-multi-i2v-std', name: 'Kling v1.6 Multi i2v Standard', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.048 },
    { id: 'kling-effects', name: 'Kling Effects', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.212 },
    { id: 'wan-2.6-t2v-alt', name: 'Wan-2.6 Text-to-video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.068 },
    { id: 'wan-2.5-t2v-fast', name: 'Wan-2.5 Text-to-video Fast', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.071 },
    { id: 'wan-2.5-t2v', name: 'Wan-2.5 Text-to-video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.035 },
    { id: 'wan-2.5-i2v', name: 'Wan-2.5 Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.035 },
    { id: 'wan-2.6-i2v-alt', name: 'Wan-2.6 Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.068 },
    { id: 'wan-2.5-i2v-fast', name: 'Wan-2.5 Image-to-video Fast', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.071 },
    { id: 'vidu-r2v-q1', name: 'Vidu Reference-to-Video Q1', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.40 },
    { id: 'vidu-r2v-2.0', name: 'Vidu Reference-to-Video 2.0', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.20 },
    { id: 'kling-2.0-i2v-master', name: 'kling v2.0 i2v Master', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.238 },
    { id: 'hailuo-02-t2v-pro', name: 'Hailuo-02 t2v Pro', provider: 'hailuo', category: 'Text-to-Video', usdPerSec: 0.49 },
    { id: 'vidu-start-end-2.0', name: 'Vidu Start-End-to-Video 2.0', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.075 },
    { id: 'kling-2.1-t2v-master', name: 'Kling v2.1 t2v Master', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.238 },
    { id: 'kling-2.0-t2v-master', name: 'Kling v2.0 t2v Master', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.238 },
    { id: 'image-to-video-2.0', name: 'Image-to-video-2.0', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.075 },
    { id: 'hailuo-02-fast', name: 'Hailuo-02 Fast', provider: 'hailuo', category: 'Image-to-Video', usdPerSec: 0.10 },
    { id: 'hailuo-02-pro', name: 'Hailuo 02 Pro', provider: 'hailuo', category: 'Image-to-Video', usdPerSec: 0.49 },
    { id: 'kling-2.1-i2v-master', name: 'Kling v2.1 i2v Master', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.238 },
    { id: 'wan-2.2-spicy-extend-lora', name: 'Wan-2.2-spicy Video Extend Lora', provider: 'laozhang', category: 'Video-to-Video', usdPerSec: 0.04 },
    { id: 'wan-2.2-spicy-extend', name: 'Wan-2.2-spicy Video Extend', provider: 'laozhang', category: 'Video-to-Video', usdPerSec: 0.032 },
    { id: 'hailuo-02-t2v-std', name: 'Hailuo 02 t2v Standard', provider: 'hailuo', category: 'Text-to-Video', usdPerSec: 0.28 },
    { id: 'hailuo-02-i2v-std', name: 'Hailuo 02 i2v Standard', provider: 'hailuo', category: 'Image-to-Video', usdPerSec: 0.28 },
    { id: 'hailuo-02-i2v-pro', name: 'Hailuo 02 i2v Pro', provider: 'hailuo', category: 'Image-to-Video', usdPerSec: 0.49 },
    { id: 'kling-2.1-i2v-pro', name: 'Kling v2.1 i2v Pro', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.083 },
    { id: 'kling-1.6-t2v-std', name: 'Kling v1.6 t2v Standard', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.048 },
    { id: 'kling-1.6-i2v-pro', name: 'Kling v1.6 i2v Pro', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.083 },
    { id: 'seedance-v1-pro-t2v-1080p', name: 'Seedance v1 Pro t2v 1080p', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.11 },
    { id: 'seedance-v1-pro-t2v-720p', name: 'Seedance v1 Pro t2v 720p', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.047 },
    { id: 'seedance-v1-pro-t2v-480p', name: 'Seedance v1 Pro t2v 480p', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.022 },
    { id: 'seedance-v1-pro-i2v-720p', name: 'Seedance v1 Pro i2v 720p', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.047 },
    { id: 'seedance-v1-pro-i2v-480p', name: 'Seedance v1 Pro i2v 480p', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.022 },
    { id: 'seedance-v1-pro-i2v-1080p', name: 'Seedance v1 Pro i2v 1080p', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.11 },
    { id: 'kling-2.1-i2v-std', name: 'Kling v2.1 i2v Standard', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.048 },
    { id: 'kling-1.6-i2v-std', name: 'Kling v1.6 i2v Standard', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.048 },
    { id: 'hailuo-02-std', name: 'Hailuo 02 Standard', provider: 'hailuo', category: 'Image-to-Video', usdPerSec: 0.28 },
    { id: 'wan-2.7-spicy-i2v', name: 'Wan 2.7 Spicy Image-to-Video', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.10 },
    { id: 'wan-2.6-spicy-i2v', name: 'Wan 2.6 Spicy Image-to-Video', provider: 'atlascloud', category: 'Image-to-Video', usdPerSec: 0.07 },
    { id: 'wan-2.5-i2v-fast-van', name: 'Van-2.5 Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.054 },
    { id: 'wan-2.2-char-swap', name: 'Wan-2.2 Video Character Swap', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.126 },
    { id: 'wan-2.2-image-to-animation', name: 'Wan-2.2 Image To Animation', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.084 },
    { id: 'wan-2.5-t2v-van', name: 'Van-2.5 Text-to-video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.068 },
    { id: 'vidu-q2-turbo-i2v', name: 'Vidu Q2-Turbo Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.026 },
    { id: 'vidu-q2-pro-fast-start-end', name: 'Vidu Q2-Pro-Fast Start-end-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.034 },
    { id: 'vidu-q2-pro-start-end', name: 'Vidu Q2-Pro Start-end-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.034 },
    { id: 'vidu-q2-turbo-start-end', name: 'Vidu Q2-Turbo Start-end-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.026 },
    { id: 'vidu-q2-pro-fast-i2v', name: 'Vidu Q2-Pro-Fast Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.034 },
    { id: 'vidu-q2-pro-i2v', name: 'Vidu Q2-Pro Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.034 },
    { id: 'vidu-q2-t2v', name: 'Vidu Q2 Text-to-video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.042 },
    { id: 'vidu-q1-i2v', name: 'Vidu Q1 Image-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.34 },
    { id: 'vidu-q1-start-end', name: 'Vidu Q1 Start-end-to-video', provider: 'laozhang', category: 'Image-to-Video', usdPerSec: 0.34 },
    { id: 'vidu-q1-t2v', name: 'Vidu Q1 Text-to-video', provider: 'laozhang', category: 'Text-to-Video', usdPerSec: 0.34 },
    { id: 'veed-fabric-1.0-i2v', name: 'Veed-fabric-1.0 Image-to-Video', provider: 'atlascloud', category: 'Audio-to-Video', usdPerSec: 0.088 },
    { id: 'veed-fabric-1.0-fast-i2v', name: 'Veed-fabric-1.0-fast Image-to-Video', provider: 'atlascloud', category: 'Audio-to-Video', usdPerSec: 0.11 }
];
