import React from 'react';
import {
    Clapperboard,
    Image,
    Type,
    Paperclip,
    Sparkles,
    Flag,
    Link2,
    Mic,
    User,
    Palette,
    Repeat,
    Scissors,
    Crop,
    RefreshCw,
    ZoomIn,
    Music,
    Film,
    Volume2,
    HelpCircle,
    Bot,
    Sliders,
    List,
    Folder,
    StickyNote,
    Layers,
    Edit3,
    Box,
    Code,
    Play,
    Tv,
    Smile,
    Video,
    Grid,
    Tag,
    Layout
} from 'lucide-react';

const ICON_MAP = {
    video_generate:    Clapperboard,
    image_generate:    Image,
    text_input:        Type,
    asset_input:       Paperclip,
    prompt_expand:     Sparkles,
    output:            Flag,
    concat:            Link2,
    stitch:            Link2,
    voiceover:         Mic,
    character_ref:     User,
    style_ref:         Palette,
    batch:             Repeat,
    trim:              Scissors,
    resize:            Crop,
    reframe:           RefreshCw,
    upscale:           ZoomIn,
    lipsync:           Volume2,
    music_sfx:         Music,
    frame_interpolate: Film,
    assistant:         Bot,
    sound_effects:     Volume2,
    video_audio_mix:   Sliders,
    list:              List,
    group:             Folder,
    sticky_note:       StickyNote,
    variations:        Layers,
    image_editor:      Edit3,
    image_to_3d:       Box,
    image_to_svg:      Code,
    svg_generator:     Code,
    svg_animation:     Play,
    video_upscaler:    Tv,
    speak:             Smile,
    edit_video_modify: Video,
    extract_frames:    Grid,
    sticker:           Tag,
    designer:          Layout,
};

export function getNodeIcon(type, size = 14) {
    const IconComponent = ICON_MAP[type] || HelpCircle;
    return <IconComponent size={size} />;
}
